terraform main VPC
vikrant-subhash/DevopsLearnings pull request #5
Opened 2022-08-09 20:37 UTC by vikrant-subhash

2022-08-09 23:05 UTC, vladimirmukhin requested changes

2022-08-09 23:05 UTC, vladimirmukhin commented on main.tf
> +}
Please remove these resources. They are not needed in terraform

2022-08-10 15:11 UTC, vladimirmukhin approved these changes

2022-08-17 15:49 UTC, vikrant-subhash commented on main.tf
> +}
this is taken care

2022-08-18 15:19 UTC, closed without merging